name: Deploy Updated Docker Image (Frontend)

on:
  repository_dispatch:
    types: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Docker Image on VM (Frontend)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop frontend-container || true
            sudo docker rm frontend-container || true
            sudo docker rmi ghcr.io/f-eighty7/chaschallenger/app:latest || true
            sudo docker pull ghcr.io/f-eighty7/chaschallenger/app:latest
            sudo docker run -d --name frontend-container -p 8080:80 --restart always -v /var/docker/frontend/logs:/var/log/app -v /var/docker/frontend/cache:/var/cache/app ghcr.io/f-eighty7/chaschallenger/app:latest
