name: Build

on:
  workflow_dispatch:
    inputs:
      trigger_backend_deploy:
        description: 'Trigger backend deploy workflow?'
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build node application
        run: npm run build

      - name: Docker login
        run: echo "${{ secrets.BACKEND_REPO_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          DOCKER_IMAGE=ghcr.io/$REPO_NAME/app:${{ github.sha }}
          docker build -t $DOCKER_IMAGE .
          docker tag $DOCKER_IMAGE ghcr.io/$REPO_NAME/app:latest
          docker push $DOCKER_IMAGE
          docker push ghcr.io/$REPO_NAME/app:latest

      - name: Trigger Backend Deploy
        if: ${{ github.event.inputs.trigger_backend_deploy == 'true' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BACKEND_REPO_ACCESS_TOKEN }}
          repository: f-eighty7/FantasyChas-Backend
          event-type: workflow_dispatch